#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '[INFO] Formatting code...'
yarn format && git add -A . 

echo '[INFO] Checking code quality...'

yarn check:format && yarn check:lint && yarn check:types && yarn build
